workflows:
  ios-release:
    name: iOS Release (TestFlight)

    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

      vars:
        BUNDLE_ID: "com.ismddch.halaqak"   # 🔥 غيرها حسب تطبيقك
        APP_STORE_APPLE_ID: "6762566697"  # 🔥 App ID من App Store Connect

    scripts:
      - name: Clean project
        script: |
          flutter clean

      - name: Get dependencies
        script: |
          flutter pub get

      - name: Analyze (اختياري لكن مهم)
        script: |
          flutter analyze || true

      - name: Run tests (اختياري)
        script: |
          flutter test || true

      - name: Build iOS (بدون توقيع)
        script: |
          flutter build ios --release --no-codesign

      - name: Install CocoaPods
        script: |
          cd ios
          pod install

      - name: Build IPA (التوقيع يتم هنا)
        script: |
          xcode-project build-ipa \
            --workspace "ios/Runner.xcworkspace" \
            --scheme "Runner"

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
