default_platform(:ios)

platform :ios do
  desc "Build Flutter iOS and upload to TestFlight using manual signing"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id:                ENV["APPSTORE_KEY_ID"],
      issuer_id:             ENV["APPSTORE_ISSUER_ID"],
      key_content:           ENV["APPSTORE_PRIVATE_KEY"],
      is_key_content_base64: false,
      duration:              1200,
      in_house:              false
    )

    update_code_signing_settings(
      use_automatic_signing: false,
      path:                  "Runner.xcodeproj",
      team_id:               ENV["TEAM_ID"],
      code_sign_identity:    "iPhone Distribution",
      profile_name:          ENV["PROVISIONING_PROFILE_NAME"],
      bundle_identifier:     ENV["APP_IDENTIFIER"]
    )

    build_app(
      workspace:     "Runner.xcworkspace",
      scheme:        "Runner",
      export_method: "app-store",
      export_options: {
        method:       "app-store",
        teamID:       ENV["TEAM_ID"],
        signingStyle: "manual",
        provisioningProfiles: {
          ENV["APP_IDENTIFIER"] => ENV["PROVISIONING_PROFILE_NAME"]
        }
      },
      output_directory: "build",
      output_name:      "Hallaqak.ipa"
    )

    upload_to_testflight(
      api_key:                           api_key,
      skip_waiting_for_build_processing: true,
      distribute_external:               false
    )
  end
end