-- VIP/Normal dual queue support
ALTER TABLE queues ADD COLUMN IF NOT EXISTS queue_type TEXT NOT NULL DEFAULT 'normal';
ALTER TABLE chairs ADD COLUMN IF NOT EXISTS vip_locked BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE chairs ADD COLUMN IF NOT EXISTS normal_locked BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE deleted_queue_entries ADD COLUMN IF NOT EXISTS queue_type TEXT NOT NULL DEFAULT 'normal';
